### PR TITLE
read ssl_verify from the config

### PR DESCRIPTION
**Pull request by KAllan357**
ssl_verify defaults to true in the nexus_cli gem. So remove most of the references to it from artifact-cookbook. Then allow ssl_verify to be configured via the data bag, so that you can override it globally.

### CODE REVIEW

**Comment by KAllan357** [comment]
```
{
  "id": "_wildcard",
  "url": "whatever",
  "repository": "whatever",
  "username": "whatever",
  "password": "whatever",
  "ssl_verify": true
}
```

**Comment by andrewGarson** [comment]
:+1:

**Comment by reset** [comment]
@KAllan357 gotta document the way to turn ssl off in the README and then :+1:

**Comment by KAllan357** [comment]
This probably should happen at some point, but I'm gonna close this without merging for now.

**Pull request closed without merging**
