### PR TITLE
Add travis and rubocop support

### PR DESCRIPTION
**Pull request by guilhem**
Use rake to test
Add documentation
Some fix

### CODE REVIEW

**Comment by BarthV** [comment]
:+1:

**Comment by KAllan357** [comment]
This is super cool! I am going to pull this in and try it out for a little bit.

**Comment by KAllan357** [comment]
Was trying this out and received the following:

```
[kallan@KAlla1ml1:~/src/artifact] (test_126) C  $ be rake style:chef
rake aborted!
Expected process to exit with [0], but received '1'
---- Begin output of vagrant --version ----
STDOUT:
STDERR: /Users/kallan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/rubygems_integration.rb:214:in `block in replace_gem': vagrant is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    from /Users/kallan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bin/vagrant:22:in `<main>'
---- End output of vagrant --version ----
Ran vagrant --version returned 1
/Users/kallan/src/artifact/Rakefile:46:in `new'
/Users/kallan/src/artifact/Rakefile:46:in `block in <top (required)>'
/Users/kallan/src/artifact/Rakefile:41:in `<top (required)>'
```

Is there possibly something wrong with my environment?

Edit: turns out I only get this error when using Bundler. Perhaps there is something wrong with the Gemfile?

**Comment by guilhem** [comment]
@KAllan357 It seems to be a problem with a previous install of vagrant (via bundler for example).

Gemfile is very generic and used in many project where I contribute to :)

**Comment by guilhem** [comment]
:up:

**Pull request merged**
