### PR TITLE
Using path attr instead of name

### PR DESCRIPTION
**Pull request by BarthV**
https://github.com/RiotGames/artifact-cookbook/issues/122

### CODE REVIEW

**Comment by KAllan357** [comment]
Forgive my confusion here, but when we have an attribute on this provider, `attribute :path, :kind_of => String, :required => true, :name_attribute => true` and a resource of:

```
artifact_file "foo" do
  path "/foo/bar/foo.tgz"
  ...
end
```

Then `new_resource.path == "/foo/bar/foo.tgz"` and `new_resource.name == "foo"`? What does it look like when there is no `path` attribute set and only name? Do both readers return the same value?

Basically, I just want to make sure we've hit all the edge cases - in (I think) all of our use cases, we use the name attribute exclusively.

**Comment by BarthV** [comment]
`:name_attribute => true` means that attribute takes resource name value by default.
You still can override this behaviour by specifying path attribute with the other resource options.

So we got something like you said :

```
no path & no name : chef error (resource name is expected)
path & no name : chef error (resource name is expected)
no path & name : path == name
path & name : path != name
```

**Comment by BarthV** [comment]
http://docs.opscode.com/lwrp_custom_resource.html :
- `:name_attribute` is associated with one `attribute` to indicate which attribute’s value will be defined by the name of the resource as it is defined in the recipe (i.e. the string that appears in front of the do block in the recipe and after the resource: `resource_name "name_attribute" do`)

So we generally have to work with the nameattribute rather than resource name directly

**Comment by KAllan357** [comment]
Thanks, this makes sense. :+1:

**Comment by BarthV** [comment]
I can you test this commit please :)

It seems that : 
`attribute :path, :kind_of => String, :required => true, :name_attribute => true`
doesn't work the same as : 
`attribute :path, :kind_of => String, :name_attribute => true, :required => true`

I never noticed this in the past but in the first case, Chef's `load_current_resource` method try to check if path is present (aka. 'required') before loading it up from lwrp name (aka. 'name_attribute').
So, currently if you don't specify path attr, it causes a break in the run : 

```
Chef::Exceptions::ValidationFailed
----------------------------------
Required argument path is missing!
```

The fix I found is to set `:name_attribute => true` before the required statement. You can also totally remove required from this line since name_attribute makes implicitly `path` attr mandatory.

Sorry for not having enough tested my patch so far ...

**Pull request merged**
